Bump up cypress version to 7.3.0
saucelabs/sauce-cypress-runner pull request #136
Opened 2021-05-19 04:24 UTC by tianfeng92

2021-05-19 08:44 UTC, FriggaHel requested changes

2021-05-19 12:23 UTC, tianfeng92 commented on tests/kitchen-sink-tests/.sauce/config.yml
> -  image: saucelabs/stt-cypress-mocha-node:local
forgot to revert it after test. Thanks!

2021-05-19 16:57 UTC, FriggaHel approved these changes

2021-05-19 18:11 UTC, merged

2021-05-20 00:39 UTC, alexplischke commented
@tianfeng92 What about https://github.com/saucelabs/sauce-cypress-runner/blob/master/Dockerfile#L9 ?