chore: Remove redundant console.log
saucelabs/sauce-cypress-runner pull request #305
Opened 2024-08-16 21:56 UTC by tianfeng92

## Description

Remove redundant console.log.

2024-08-16 22:38 UTC, mhan83 approved these changes

2024-08-16 22:40 UTC, mhan83 requested changes
This needs to be removed too? 

https://github.com/saucelabs/sauce-cypress-runner/blob/main/package.json#L8

Or do we need to keep `bin/cypress`? `npm  test` runs it

2024-08-16 22:45 UTC, alexplischke approved these changes

2024-08-16 22:52 UTC, tianfeng92 commented
> This needs to be removed too?
> 
> https://github.com/saucelabs/sauce-cypress-runner/blob/main/package.json#L8
> 
> Or do we need to keep `bin/cypress`? `npm test` runs it

Nice catch. Let me check `npm test`.

2024-08-17 00:21 UTC, alexplischke approved these changes

2024-08-19 16:03 UTC, merged